apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmos-wallets-exporter.fullname" . }}-config
  labels:
    {{- include "cosmos-wallets-exporter.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- include "cosmos-wallets-exporter.processedConfig" . | nindent 4 }} 