name: Build image and push to ghcr.io

on:
  push:
    branches:
      - main
      - master
  workflow_run:
    workflows: ["test"]
    types:
      - completed
    branches:
      - main
      - master
  workflow_dispatch: # Added to enable manual trigger via GitHub UI

jobs:
  build-and-push:
    runs-on: "ubuntu-22.04"
    # Only run if the test workflow succeeded (when triggered by workflow_run)
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git describe to work properly for versioning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: |
            ghcr.io/quokkastake/cosmos-wallets-exporter
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag,suffix=-rc
            type=sha,format=short,suffix=-rc
            type=ref,event=branch,pattern=latest
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64 #,linux/arm64
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
